version: "3.8"

services:  
  client:
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile.dev
      context: ./src/client
    volumes:
      - /app/node_modules
      - ./src/client:/app
    depends_on:
      - api
    ports: 
      - 3500:3500

  api:
    build:
      dockerfile: Dockerfile.dev
      context: "./src/server"
    volumes:
      - /app/node_modules
      - ./src/server:/app
    restart: always
    depends_on: 
      - db
    # environment:
    #   - PGUSER=postgres
    #   - PGHOST=postgres
    #   - PGDATABASE=postgres
    #   - PGPASSWORD=postgres_password
    #   - PGPORT=5432
    ports: 
      - 5000:5000

  db:
    image: "mongo:latest"
    restart: unless-stopped
    volumes:
      - "/data/mongo-db:/data/db"
    ports: 
      - 6969:2717
