version: "3.8"

services:
  # student-obrok-client:
  #   image: student-obrok-client:latest
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - student-obrok-server
  # student-obrok-server:
  #   image: student-obrok-server:latest
  #   ports:
  #     - "6969:6969"
  #   depends_on: 
  #     - student-obrok-db
  student-obrok-db:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "6969:27017"
    volumes:
      - "/data/mongo-db:/data/db"
