services:
  osrm:
    container_name: obrok_osrm
    image: osrm/osrm-backend
    volumes:
      - ./data/map:/data
    command: osrm-routed --algorithm mld /data/macedonia-latest.osrm
    ports:
      - 5001:5000

  nginx:
    image: nginx:alpine
    container_name: obrok_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - client
      - api
      - osrm
      - certbot
      
  client:
    container_name: obrok_client
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile.prod
      context: ./src/client
    volumes:
      - /app/node_modules
      - ./src/client:/app
    environment:
      NODE_ENV: production
    ports:
      - 3500:3500
    depends_on:
      - api

  api:
    container_name: obrok_api
    build:
      dockerfile: Dockerfile.prod
      context: ./src/server
    volumes:
      - /app/node_modules
      - ./src/server:/app
    restart: always
    environment:
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      DATABASE_URI: ${DATABASE_URI}
      PORT: ${PORT}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CLIENT_ORIGIN: ${CLIENT_ORIGIN}
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    container_name: obrok_db
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - student_obrok_db:/data/db

  certbot:
    image: certbot/certbot
    container_name: obrok_certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

volumes:
  student_obrok_db:
