services:
  client:
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile.prod
      context: ./src/client
    volumes:
      - /app/node_modules
      - ./src/client:/app
    environment:
      NODE_ENV: production
    ports:
      - 3500:3500
    depends_on:
      - api

  api:
    build:
      dockerfile: Dockerfile.prod
      context: "./src/server"
    volumes:
      - /app/node_modules
      - ./src/server:/app
    restart: always
    environment:
      ACCESS_TOKEN_SECRET: "${ACCESS_TOKEN_SECRET}"
      REFRESH_TOKEN_SECRET: "${REFRESH_TOKEN_SECRET}"
      DATABASE_URI: "${DATABASE_URI}"
      PORT: "${PORT}"
      ADMIN_USERNAME: "${ADMIN_USERNAME}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "6969:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE}"
    volumes:
      - "/data/studentObrokDb:/data/db"
