services:
  osrm:
    image: osrm/osrm-backend 
    volumes:
      - ./data/map:/data
    command: osrm-routed --algorithm mld /data/macedonia-latest.osrm
    ports:
      - 5001:5000
 
  client:
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile.dev
      context: ./src/client
    volumes:
      - /app/node_modules
      - ./src/client:/app
    environment:
      NODE_ENV: development
    depends_on:
      - api
    ports: 
      - 3500:3500

  api:
    build:
      dockerfile: Dockerfile.dev
      context: "./src/server"
    volumes:
      - /app/node_modules
      - ./src/server:/app
    environment:
      ACCESS_TOKEN_SECRET: "${ACCESS_TOKEN_SECRET}"
      REFRESH_TOKEN_SECRET: "${REFRESH_TOKEN_SECRET}"
      DATABASE_URI: "${DATABASE_URI}"
      PORT: "${PORT}"
      ADMIN_USERNAME: "${ADMIN_USERNAME}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      CLIENT_ORIGIN: "${CLIENT_ORIGIN}"
    restart: always
    depends_on: 
      - db
    ports: 
      - 5000:5000

  db:
    image: mongo:latest
    ports:
      - "6969:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE}"
    volumes:
      - student_obrok_db:/data/db

volumes:
  student_obrok_db: