services:
  nginx:
    container_name: obrok_nginx
    build:
      context: ./apps/client
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    volumes:
      - ./apps/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    environment:
      NODE_ENV: production
    ports:
      - 80:80
      - 443:443

  certbot:
    container_name: obrok_certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --keep-until-expiring --email ${CERTBOT_EMAIL} -d obrok.net --agree-tos

  osrm:
    container_name: obrok_osrm
    image: osrm/osrm-backend
    volumes:
      - ./data/map:/data
    command: osrm-routed --algorithm mld /data/macedonia-latest.osrm
    ports:
      - 5001:5000

  api:
    container_name: obrok_api
    build:
      context: ./apps/server
      dockerfile: Dockerfile.prod
    volumes:
      - /app/node_modules
      - ./apps/server:/app
    restart: always
    environment:
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      DATABASE_URI: ${DATABASE_URI}
      PORT: ${PORT}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CLIENT_ORIGIN: ${CLIENT_ORIGIN}
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    container_name: obrok_db
    image: mongo:latest
    ports:
      - 6969:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - student_obrok_db:/data/db

volumes:
  student_obrok_db:
