services:
  osrm:
    container_name: obrok_osrm
    image: osrm/osrm-backend
    volumes:
      - ./data/map:/data
    command: osrm-routed --algorithm mld --port 5001 /data/macedonia-latest.osrm
    ports:
      - 5001:5001
    networks:
      - obrok_net

  client:
    container_name: obrok_client
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile.dev
      context: ./apps/client
    volumes:
      - client_node_modules:/app/node_modules
      - ./apps/client:/app
    environment:
      NODE_ENV: development
    ports:
      - 3500:3500
    depends_on:
      - api
    networks:
      - obrok_net

  api:
    container_name: obrok_api
    build:
      dockerfile: Dockerfile.dev
      context: ./apps/server
    volumes:
      - server_node_modules:/app/node_modules
      - ./apps/server:/app
    env_file:
      - .env
    environment:
      NODE_ENV: development
    restart: always
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - obrok_net

  db:
    container_name: obrok_db
    image: mongo:8.0
    ports:
      - 6969:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: obrok
    volumes:
      - student_obrok_db:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - obrok_net

networks:
  obrok_net:
    driver: bridge

volumes:
  student_obrok_db:
  client_node_modules:
  server_node_modules: