name: CI/CD Workflow

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  gitlab-sync:
    name: gitlab-sync
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Push to GitLab
        env:
          GITLAB_REMOTE_URL: ${{ secrets.GITLAB_REMOTE_URL }}
          GITLAB_MAIL: ${{ secrets.GITLAB_MAIL }}
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_DEPLOY_KEY: ${{ secrets.GITLAB_DEPLOY_KEY }}
        run: |
          git config --global user.email "${GITLAB_MAIL}"
          git config --global user.name "${GITLAB_USERNAME}"
          
          # Configure SSH key
          mkdir -p ~/.ssh
          echo "$GITLAB_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan gitlab.finki.ukim.mk >> ~/.ssh/known_hosts
          
          # Add GitLab remote and push
          git remote add gitlab "${GITLAB_REMOTE_URL}"
          git push gitlab main:main --force
