name: CI/CD Workflow

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  gitlab-sync:
    name: gitlab-sync
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Push to GitLab
        env:
          GITLAB_URL: ${{ secrets.GITLAB_REMOTE_URL }}
          GITLAB_MAIL: ${{ secrets.GITLAB_MAIL }}
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_DEPLOY_TOKEN: ${{ secrets.GITLAB_DEPLOY_TOKEN }}
        run: |
          git config --global user.email "${GITLAB_MAIL}"
          git config --global user.name "${GITLAB_USERNAME}"
    
          git remote add gitlab "https://${GITLAB_USERNAME}:${GITLAB_DEPLOY_TOKEN}@gitlab.finki.ukim.mk/193254/student-obrok.git"

          git push gitlab main:main --force
