name: Docs CI

on:
  pull_request:
    paths:
      - "apps/docs/**"
      - ".github/workflows/docs-ci.yml"

jobs:
  docs-build:
    name: Build Documentation
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./apps/docs

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install docs dependencies
        run: npm ci

      - name: Build docs
        run: npm run docs:build
